# Generated by Django 5.1.1 on 2024-10-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Row', models.IntegerField()),
                ('Column', models.CharField(max_length=255)),
                ('ComparedValue', models.CharField(max_length=255)),
                ('OriginalValue', models.CharField(max_length=255)),
            ],
        ),
    ]
